Token: "Bot_Token"
License: "85148373-4827-4e6d-ae4d-f3eba0109480"
Channel_id:
  Message: '794157898930323456'
  Serveur: '794157898930323456'
  JoinLeave: "794157898930323456"
  Achievement: '794157898930323456'
  Death: '794157898930323456'

Message:
  Message: '%player% >> %message%'
  ServeurOpen: "Serveur en ligne"
  ServeurClose: "Serveur en hors-ligne"
  Join: "%player% à rejoint le serveur !"
  Leave: "%player% à quitté le serveur !"
  Achievement: "%player% viens d'obtenir %achievement%"
  Death: '%player% viens de mourir!'
  CompteCheck: 'Votre compte est deja verifié'
  CodeGive: "/discord link %code%"
  Discord: "[discord] %user% >> %message%"
  BadUsage: ">>> /discord link <code>"
  Update: "Compte discord update"
  BadCode: ">>> Code invalide"

advancementMap:
  "story/mine_stone": "L'âge de pierre"
  "story/upgrade_tools": "Qualité supérieure"
  "story/smelt_iron": "L'âge du fer"
  "story/obtain_armor": "Un corps d'acier"
  "story/lava_bucket": "Ça brûle !"
  "story/iron_tools": "Bonne pioche !"
  "story/deflect_arrow": "Pas aujourd'hui, merci"
  "story/form_obsidian": "Ice Bucket Challenge"
  "story/mine_diamond": "Des diamants !"
  "story/enter_the_nether": "Aller au fond des choses"
  "story/shiny_gear": "Couvrez-moi de diamants"
  "story/enchant_item": "Enchanté !"
  "story/cure_zombie_villager": "Zombiologue"
  "story/follow_ender_eye": "À suivre…"
  "story/enter_the_end": "Fin?"
  "nether/return_to_sender": "Retour à l'envoyeur"
  "nether/find_bastion": "Le bon vieux temps"
  "nether/obtain_ancient_debris": "Caché dans les profondeurs"
  "nether/fast_travel": "Bulle du sous-espace"
  "nether/find_fortress": "Une terrible forteresse"
  "nether/obtain_crying_obsidian": "Qui a coupé un oignon ?"
  "nether/distract_piglin": "Bling-bling"
  "nether/ride_strider": "Bateau sur pattes"
  "nether/uneasy_alliance": "Alliance instable"
  "nether/loot_bastion": "De vraies têtes de cochon"
  "nether/use_lodestone": "Le Petit Poucet"
  "nether/netherite_armor": "Cover Me in Debris"
  "nether/get_wither_skull": "Couvrez-moi de débris"
  "nether/obtain_blaze_rod": "Dans le feu de l'action"
  "nether/charge_respawn_anchor": "Pas tout à fait \"neuf\" vies"
  "nether/explore_nether": "Voyage au bout de l'enfer"
  "nether/summon_wither": "Les Witherables"
  "nether/brew_potion": "Apprenti chimiste"
  "nether/create_beacon": "Fais ta balise"
  "nether/all_potions": "Mélanges dangereux"
  "nether/create_full_beacon": "Phare à On"
  "nether/all_effects": "Comment en est-on arrivé là ?"
  "end/kill_dragon": "Libérez l'End !"
  "end/dragon_egg": "La nouvelle génération"
  "end/enter_end_gateway": "Escapade à distance"
  "end/respawn_dragon": "Un air de déjà vu..."
  "end/dragon_breath": "À bout de souffle"
  "end/find_end_city": "La cité du bout du monde"
  "end/elytra": "Vers l'infini et au-delà"
  "end/levitate": "Superbe panorama"
  "adventure/voluntary_exile": "Exil volontaire"
  "adventure/kill_a_mob": "Chasseur de monstres"
  "adventure/trade": "Adjugé, vendu !"
  "adventure/honey_block_slide": "tterrissage en douceur"
  "adventure/ol_betsy": "La vieille Bertha"
  "adventure/sleep_in_bed": "Bonne nuit les petits"
  "adventure/hero_of_the_village": "Héros du village"
  "adventure/throw_tident": "Une blague tombée à l'eau"
  "adventure/shoot_arrow": "Dans la ligne de mire"
  "adventure/kill_all_mobs": "Monstres chassés"
  "adventure/totem_of_undying": "Aux frontières de la mort"
  "adventure/summon_iron_golem": "Agent de sécurité"
  "adventure/two_birds_one_arrow": "D'une flèche deux coups"
  "adventure/whos_the_pillager_now": "C'est qui le pillard maintenant ?"
  "adventure/arbalistic": "Arbalistique"
  "adventure/adventuring_time": "Partons à l'aventure !"
  "adventure/very_very_frightening": "Coup de foudre"
  "adventure/sniper_duel": "Duel de snipers"
  "adventure/bullseye": "Dans le mille !"
  "husbandry/safely_harvest_honey": "J'irai butiner chez vous"
  "husbandry/breed_an_animal": "Il y a de l'amour dans l'air"
  "husbandry/tame_an_animal": "Meilleurs amis pour la vie"
  "husbandry/fishy_business": "Merci pour le poisson"
  "husbandry/silk_touch_nest": "Total Beelocation"
  "husbandry/plant_seed": "A Seedy Place"
  "husbandry/breed_all_animals": "Two by Two"
  "husbandry/complete_catalogue": "A Complete Catalogue"
  "husbandry/tactical_fishing": "Pêche tactique"
  "husbandry/balanced_diet": "Une alimentation équilibrée"
  "husbandry/obtain_netherite_hoe": "Sérieux dévouement"